routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@home')->name('home');
Route::get('/profile', 'ProfileController@profile')->name('profiles.index');
Route::post('/profile', 'ProfileController@update')->name('profiles.update');

Route::resources([
    'users' => 'UserController',
    'admins' => 'AdminController',
    'tags' => 'TagController',
]);

Route::group(['namespace' => 'Course', 'prefix' => 'course', 'as' => 'course.'], function () {
    Route::resources([
        'instructors' => 'InstructorController',
        'courses' => 'CourseController',
        'syllabuses' => 'SyllabusController',
        'categories' => 'CategoryController',
    ]);
});

Route::group(['namespace' => 'Exam', 'prefix' => 'exam' , 'as' => 'exam.'], function () {
    Route::resources([
        'exams' => 'ExamController',
        'questions' => 'QuestionController',
    ]);
});

Route::group(['namespace' => 'Blog', 'prefix' => 'blog', 'as' => 'blog.'], function () {
    Route::resources([
        'posts' => 'PostController',
    ]);

    Route::get('/comments/', 'CommentController@index')->name('posts.comments.index');
    Route::delete('/comments/{comment}', 'CommentController@destroy')->name('posts.comments.destroy');
});

Route::group(['namespace' => 'Shop', 'prefix' => 'shop', 'as' => 'shop.'], function () {
    Route::resources([
        'products' => 'ProductController',
        'categories' => 'CategoryController',
    ]);

    Route::post('/products/{product}/change-status', 'ProductController@changeStatus')->name('products.change-status');

    Route::get('/comments/', 'CommentController@index')->name('products.comments.index');
    Route::delete('/comments/{comment}', 'CommentController@destroy')->name('products.comments.destroy');

    Route::get('/orders/', 'OrderController@index')->name('orders.index');
    Route::post('/orders/{order}/change-status', 'OrderController@changeStatus')->name('orders.change-status');
});

Route::get('/transactions/', 'TransactionController@index')->name('transactions.index');

Route::get('/contact-form/', 'ContactFormController@index')->name('contact-form.index');

routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@home')->name('home');

Route::post('/profile/update', 'ProfileController@update')->name('profile.update');
Route::post('/profile/image/update', 'ProfileController@imageUpdate')->name('profile.image.update');
Route::post('/profile/password/update', 'ProfileController@changePassword')->name('profile.password.change');


Route::group(['prefix' => 'products'], function () {
    Route::post('/', 'ProductController@store')->name('products.store');
    Route::post('/datatable', 'ProductController@datatable')->name('products.datatable');
});

Route::group(['prefix' => 'orders'], function () {
    Route::delete('destroy/{order}', 'OrderController@destroy')->name('orders.destroy');
    Route::get('show/{order}', 'OrderController@show')->name('orders.show');
    Route::get('pay/{order}', 'OrderController@pay')->name('orders.pay');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
    Route::get('/otp', [
        'uses' => 'OtpController@show',
        'as' => 'auth.otp',
        'middleware' => 'guest',
    ]);
    Route::post('/otp/request', [
        'uses' => 'OtpController@request',
        'as' => 'auth.otp.request',
        'middleware' => ['throttle:3,1', 'guest'],
    ]);
    Route::post('/otp/submit', [
        'uses' => 'OtpController@submit',
        'as' => 'auth.otp.submit',
        'middleware' => ['throttle:3,1', 'guest'],
    ]);

    Route::get('sign-up', [
        'uses' => 'SignUpController@show',
        'as' => 'auth.sign-up',
        'middleware' => 'auth',
    ]);
    Route::post('sign-up', [
        'uses' => 'SignUpController@request',
        'middleware' => 'auth',
    ]);

    Route::get('sign-in', [
        'uses' => 'SignInController@show',
        'as' => 'auth.sign-in',
        'middleware' => 'guest',
    ]);
    Route::post('sign-in', [
        'uses' => 'SignInController@request',
        'middleware' => 'guest',
    ]);
    Route::get('sign-out', [
        'uses' => 'SignOutController@handle',
        'as' => 'auth.sign-out',
    ]);
});

//verify email
Route::get('/account/email/verify/{token}', [
    'uses' => 'Account\EmailResetController@verify',
    'as' => 'account.email.verify',
]);

// get all cities of province
Route::get('/cities', 'CityController@get')->name('cities');

Route::post('/upload/image', 'uploadController@dropzone')->name('upload.dropzone');

Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'HomeController@home')->name('home');

    Route::get('/contact-us', 'ContactUsController@show')->name('contact-us');
    Route::post('/contact-us', 'ContactUsController@request');

    Route::get('/search', 'SearchController@search')->name('search');
    Route::get('/courses/search', 'SearchController@courseSearch')->name('course.search');
    Route::get('/posts/search', 'SearchController@postSearch')->name('post.search');
    Route::get('/products/search', 'SearchController@productSearch')->name('product.search');

    Route::group(['prefix' => 'courses', 'namespace' => 'Course'], function () {
        Route::get('/', 'CourseController@index')->name('courses.index');
        Route::get('/{course}/{slug?}', 'CourseController@show')->name('courses.show');

        Route::post('/{course}/reactions', ['as' => 'courses.react', 'uses' => 'CourseController@react']);


        Route::group(['prefix' => 'syllabuses'], function () {
            Route::get('/{syllabus}/{slug?}', 'SyllabusController@show')->name('syllabuses.show');
        });

        Route::get('/instructors/{instructor}/{slug?}', 'InstructorController@show')->name('instructors.show');
    });

    Route::group(['prefix' => 'articles', 'namespace' => 'Blog'], function () {
        Route::get('/', 'PostController@index')->name('posts.index');
        Route::get('/filter', 'PostController@filter')->name('posts.filter');
        Route::get('/{post}/{slug?}', 'PostController@show')->name('posts.show');

        Route::resource('posts.comments', 'CommentController')->shallow();
    });

    Route::group(['prefix' => 'shop', 'namespace' => 'Shop'], function () {
        Route::get('/', 'ShopController@index')->name('shop.index');
        Route::post('/products/datatable', 'ShopController@datatable')->name('shop.products.datatable');
        Route::get('/products/{id}/{slug?}', 'ShopController@product')->name('shop.products.show');
        Route::get('/cart', 'CartController@show')->name('shop.cart.show');
        Route::get('/cart/{product}/{count}', 'CartController@add')->name('shop.cart.add');
        Route::get('/checkout', 'ShopController@checkout')->name('shop.checkout');
        Route::get('/checkout', 'ShopController@checkout')->name('shop.checkout');

        Route::get('/orders/{order}', 'OrderController@show')->name('orders.show');
        Route::post('/orders', 'OrderController@store')->name('orders.store');
        Route::delete('/orders/{order}', 'OrderController@destroy')->name('orders.destroy');

        Route::resource('products.comments', 'CommentController')->shallow();
    });

    Route::group(['prefix' => 'schools', 'namespace' => 'School'], function () {
        Route::get('/{school}', 'SchoolController@show')->name('schools.show');
    });

    Route::group(['prefix' => 'provinces', 'namespace' => 'Province'], function () {
        Route::get('/', 'ProvinceController@index')->name('provinces.index');
        Route::get('/{province}', 'ProvinceController@show')->name('provinces.show');
    });

    Route::get('/invoices/{invoice}', 'InvoiceController@show')->name('invoices.show');
    Route::post('/invoices/{invoice}/pay', 'InvoiceController@pay')->name('invoices.pay');

    Route::any('/payment/callback/{gateway}/{invoice}', 'PaymentController@callback')->name('payment.callback');
});

app/Models/Instructor.php
<?php

namespace App\Models;

use App\Enums\Instructor\InstructorType;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\Translation\Translator;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * App\Models\Instructor
 *
 * @property int $id
 * @property int $type
 * @property int|null $user_id
 * @property string $name
 * @property string $title
 * @property string|null $about
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read string|null $image
 * @property-read string $slug
 * @property-read User|null $user
 * @method static \Illuminate\Database\Eloquent\Builder|Instructor newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Instructor newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Instructor query()
 * @method static \Illuminate\Database\Eloquent\Builder|Instructor whereAbout($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Instructor whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Instructor whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Instructor whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Instructor whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Instructor whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Instructor whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Instructor whereUserId($value)
 * @mixin \Eloquent
 */
class Instructor extends Model
{
    /**
     * @var string[]
     */
    protected $fillable = [
        'id', 'name', 'about', 'user_id', 'title', 'type',
    ];

    /**
     * @param $value
     * @return string
     */
    public function getNameAttribute($value)
    {
        return ($this->type == InstructorType::User) ? $this->user->full_name : $value;
    }

    /**
     * @return string|null
     */
    public function getImageAttribute()
    {
        return isset($this->user) ? $this->user->image : null;
    }

    /**
     * @return string
     */
    public function getSlugAttribute()
    {
        return slugify($this->name);
    }

    /**
     * @return array|Application|Translator|string|null
     */
    public function type()
    {
        return InstructorType::translatedKeyOf($this->type);
    }

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/Course/InstructorController.php
<?php

namespace App\Http\Controllers\Admin\Course;

use App\Enums\Instructor\InstructorType;
use App\Http\Controllers\Controller;
use App\Models\Instructor;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class InstructorController extends Controller
{
    /**
     * @return Factory|View
     */
    public function index()
    {
        $instructors = Instructor::paginate(15);

        return view('pages.admin.instructor.index', [
            'instructors' => $instructors
        ]);
    }

    /**
     * @return Factory|View
     */
    public function create()
    {
        return view('pages.admin.instructor.create');
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'title' => 'required',
            'about' => 'required|max:1024',
        ]);

        $instructor = new Instructor();
        $instructor->type = InstructorType::NotUser;
        $instructor->name = $request->get('name');
        $instructor->title = $request->get('title');
        $instructor->about = $request->get('about');
        $instructor->save();

        return redirect()-> route('admin.course.instructors.index')->with('success', trans('instructors.created'));
    }

    /**
     * @param int $id
     */
    public function show($id)
    {
        //
    }

    /**
     * @param int $id
     *  @return Factory|View
     */
    public function edit($id)
    {
        $instructor = Instructor::findOrFail($id);

        return view('pages.admin.instructor.edit', [
            'instructor' => $instructor,
        ]);
    }

    /**
     * @param Request $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'title' => 'required',
            'about' => 'required|max:1024',
        ]);

        $instructor = Instructor::findOrFail($id);
        $instructor->name = $request->get('name');
        $instructor->title = $request->get('title');
        $instructor->about = $request->get('about');
        $instructor->save();

        return redirect()-> route('admin.course.instructors.index')->with('success', trans('instructors.updated'));
    }

    /**
     * @param int $id
     * @return JsonResponse
     * @throws Exception
     */
    public function destroy($id)
    {
        Instructor::whereId($id)->where('type', InstructorType::NotUser)->delete();

        return new JsonResponse(['message' => trans('categories.deleted')]);
    }
}

app/Http/Controllers/Front/Course/InstructorController.php
<?php

namespace App\Http\Controllers\Front\Course;

use App\Http\Controllers\Controller;
use App\Models\Course;
use App\Models\Instructor;
use Illuminate\Contracts\View\Factory;
use Illuminate\View\View;

class InstructorController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param Instructor $instructor
     * @return Factory|View
     */
    public function show(Instructor $instructor)
    {
        $courses = Course::whereInstructorId($instructor->id)->orderBy('id', 'desc')->whereHas('syllabuses')->limit(6)->paginate(16);

        return view('pages.front.course.instructor', [
            'instructor' => $instructor,
            'courses' => $courses,
        ]);
    }
}

resources/views/pages/admin/instructor/create.blade.php
@extends('pages.admin.layout.base')

@section('title', 'خانه')
@section('instructor', 'active menu-open')
@section('instructor2', 'active')

@section('header')
    <section class="content-header">
        <h1>
            افزودن مدرس جدید
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home')}}"><i class="fa fa-dashboard"></i>خانه</a></li>
            <li><a href="#">مدرسان</a></li>
            <li class="active">افزودن مدرس</li>
        </ol>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <form method="post" action="{{ route('admin.course.instructors.store')}}">
                        @csrf
                        <div class="box-header"></div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">نام</label>
                                        <input type="text" class="form-control" id="name" name="name"
                                               value="{{ old('name')}}" placeholder="نام">
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="title">
                                            لقب / سمت / شغل ( برای مثال استاد دانشگاه)
                                        </label>
                                        <input type="text" class="form-control" id="title" name="title"
                                               value="{{ old('title')}}" placeholder="عنوان">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <label for="about">توضیحات </label>
                                    <textarea id="about" name="about" class="form-control">{{old('about')}}</textarea>
                                </div>
                            </div>

                        </div>
                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">افزودن مدرس جدید</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/admin/instructor/edit.blade.php
@extends('pages.admin.layout.base')

@section('title', 'خانه')
@section('instructor', 'active menu-open')
@section('instructor1', 'active')

@section('header')
    <section class="content-header">
        <h1>
            ویرایش مدرس
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i>خانه</a></li>
            <li><a href="#">مدرسان</a></li>
            <li class="active">ویرایش مدرس</li>
        </ol>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <form method="post" action="{{ route('admin.course.instructors.update', ['instructor' => $instructor]) }}">
                        @method('PUT')
                        @csrf
                        <div class="box-header"></div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">نام</label>
                                        <input type="text" class="form-control" id="name" name="name"
                                               value="{{ old('name', $instructor->name) }}" placeholder="نام">
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="title">
                                            لقب / سمت / شغل ( برای مثال استاد دانشگاه)
                                        </label>
                                        <input type="text" class="form-control" id="title" name="title"
                                               value="{{ old('title', $instructor->title) }}" placeholder="عنوان">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <label for="about">توضیحات </label>
                                    <textarea id="about" name="about" class="form-control">{{old('about', $instructor->about) }}</textarea>
                                </div>
                            </div>

                        </div>
                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">ویرایش</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/admin/instructor/index.blade.php
@extends('pages.admin.layout.base')

@section('title', 'خانه')
@section('instructor', 'active menu-open')
@section('instructor1', 'active')

@section('header')
    <section class="content-header">
        <h1>
            مدرسان <small>لیست</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i>خانه</a></li>
            <li><a href="#">مدرسان</a></li>
            <li class="active">لیست مدرسان</li>
        </ol>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">لیست مدرسان</h3>
                        <a href="{{ route('admin.course.instructors.create') }}" class="btn btn-primary btn-flat pull-left">افزودن
                            مدرس جدید</a>
                    </div>
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>نام</th>
                                <th>توضیحات</th>
                                <th>نوع</th>
                                <th>تاریخ ایجاد</th>
                                <th>عملیات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($instructors as $instructor)
                                <tr>
                                    <td>{{ $instructor->name}}</td>
                                    <td>{{substr($instructor->about,0,200) }}</td>
                                    <td>{{ $instructor->type() }}</td>
                                    <td>{{jDate($instructor->created_at, 'dd MMMM yyyy - HH:mm') }}</td>
                                    <td>
                                        @if($instructor->type = \App\Enums\Instructor\InstructorType::NotUser)
                                            <a href="{{  route('admin.course.instructors.edit', ['instructor' => $instructor->id]) }}"
                                               type="button" class="btn btn-block btn-primary btn-xs">
                                                ویرایش مدرس
                                            </a>
                                            <a type="button" class="btn btn-block btn-danger btn-xs"
                                               onclick="removeInstructor({{ $instructor->id}})">
                                                حذف مدرس
                                            </a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="mt-2">
                            {{ $instructors->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('js')
    <script>
        function removeInstructor(id) {
            let url = "{{ route('admin.course.instructors.destroy', '') }}/" + id
            Swal.fire({
                title: 'آیا مدرس حذف شود؟',
                text: "",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'بله',
                cancelButtonText: 'خیر',
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: "DELETE",
                        url: url,
                        success: function (response) {
                            Swal.fire(
                                'مدرس با موفقیت حذف شد',
                                '',
                                'success'
                            )
                            window.location.reload();
                        },
                        error: function (error) {
                            switch (error.status) {
                                case 422:
                                    let errors = error['responseJSON']['errors'];

                                    for (let i in errors) {
                                        toastr.error(errors[i])
                                    }
                                    break;
                                default:
                                    // 500
                                    toastr.error(error['responseJSON']['message'])
                                    break;
                            }
                        }
                    });
                }
            })
        }
    </script>
@endsection