routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@home')->name('home');
Route::get('/profile', 'ProfileController@profile')->name('profiles.index');
Route::post('/profile', 'ProfileController@update')->name('profiles.update');

Route::resources([
    'users' => 'UserController',
    'admins' => 'AdminController',
    'tags' => 'TagController',
]);

Route::group(['namespace' => 'Course', 'prefix' => 'course', 'as' => 'course.'], function () {
    Route::resources([
        'instructors' => 'InstructorController',
        'courses' => 'CourseController',
        'syllabuses' => 'SyllabusController',
        'categories' => 'CategoryController',
    ]);
});

Route::group(['namespace' => 'Exam', 'prefix' => 'exam' , 'as' => 'exam.'], function () {
    Route::resources([
        'exams' => 'ExamController',
        'questions' => 'QuestionController',
    ]);
});

Route::group(['namespace' => 'Blog', 'prefix' => 'blog', 'as' => 'blog.'], function () {
    Route::resources([
        'posts' => 'PostController',
    ]);

    Route::get('/comments/', 'CommentController@index')->name('posts.comments.index');
    Route::delete('/comments/{comment}', 'CommentController@destroy')->name('posts.comments.destroy');
});

Route::group(['namespace' => 'Shop', 'prefix' => 'shop', 'as' => 'shop.'], function () {
    Route::resources([
        'products' => 'ProductController',
        'categories' => 'CategoryController',
    ]);

    Route::post('/products/{product}/change-status', 'ProductController@changeStatus')->name('products.change-status');

    Route::get('/comments/', 'CommentController@index')->name('products.comments.index');
    Route::delete('/comments/{comment}', 'CommentController@destroy')->name('products.comments.destroy');

    Route::get('/orders/', 'OrderController@index')->name('orders.index');
    Route::post('/orders/{order}/change-status', 'OrderController@changeStatus')->name('orders.change-status');
});

Route::get('/transactions/', 'TransactionController@index')->name('transactions.index');

Route::get('/contact-form/', 'ContactFormController@index')->name('contact-form.index');

routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@home')->name('home');

Route::post('/profile/update', 'ProfileController@update')->name('profile.update');
Route::post('/profile/image/update', 'ProfileController@imageUpdate')->name('profile.image.update');
Route::post('/profile/password/update', 'ProfileController@changePassword')->name('profile.password.change');


Route::group(['prefix' => 'products'], function () {
    Route::post('/', 'ProductController@store')->name('products.store');
    Route::post('/datatable', 'ProductController@datatable')->name('products.datatable');
});

Route::group(['prefix' => 'orders'], function () {
    Route::delete('destroy/{order}', 'OrderController@destroy')->name('orders.destroy');
    Route::get('show/{order}', 'OrderController@show')->name('orders.show');
    Route::get('pay/{order}', 'OrderController@pay')->name('orders.pay');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
    Route::get('/otp', [
        'uses' => 'OtpController@show',
        'as' => 'auth.otp',
        'middleware' => 'guest',
    ]);
    Route::post('/otp/request', [
        'uses' => 'OtpController@request',
        'as' => 'auth.otp.request',
        'middleware' => ['throttle:3,1', 'guest'],
    ]);
    Route::post('/otp/submit', [
        'uses' => 'OtpController@submit',
        'as' => 'auth.otp.submit',
        'middleware' => ['throttle:3,1', 'guest'],
    ]);

    Route::get('sign-up', [
        'uses' => 'SignUpController@show',
        'as' => 'auth.sign-up',
        'middleware' => 'auth',
    ]);
    Route::post('sign-up', [
        'uses' => 'SignUpController@request',
        'middleware' => 'auth',
    ]);

    Route::get('sign-in', [
        'uses' => 'SignInController@show',
        'as' => 'auth.sign-in',
        'middleware' => 'guest',
    ]);
    Route::post('sign-in', [
        'uses' => 'SignInController@request',
        'middleware' => 'guest',
    ]);
    Route::get('sign-out', [
        'uses' => 'SignOutController@handle',
        'as' => 'auth.sign-out',
    ]);
});

//verify email
Route::get('/account/email/verify/{token}', [
    'uses' => 'Account\EmailResetController@verify',
    'as' => 'account.email.verify',
]);

// get all cities of province
Route::get('/cities', 'CityController@get')->name('cities');

Route::post('/upload/image', 'uploadController@dropzone')->name('upload.dropzone');

Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'HomeController@home')->name('home');

    Route::get('/contact-us', 'ContactUsController@show')->name('contact-us');
    Route::post('/contact-us', 'ContactUsController@request');

    Route::get('/search', 'SearchController@search')->name('search');
    Route::get('/courses/search', 'SearchController@courseSearch')->name('course.search');
    Route::get('/posts/search', 'SearchController@postSearch')->name('post.search');
    Route::get('/products/search', 'SearchController@productSearch')->name('product.search');

    Route::group(['prefix' => 'courses', 'namespace' => 'Course'], function () {
        Route::get('/', 'CourseController@index')->name('courses.index');
        Route::get('/{course}/{slug?}', 'CourseController@show')->name('courses.show');

        Route::post('/{course}/reactions', ['as' => 'courses.react', 'uses' => 'CourseController@react']);


        Route::group(['prefix' => 'syllabuses'], function () {
            Route::get('/{syllabus}/{slug?}', 'SyllabusController@show')->name('syllabuses.show');
        });

        Route::get('/instructors/{instructor}/{slug?}', 'InstructorController@show')->name('instructors.show');
    });

    Route::group(['prefix' => 'articles', 'namespace' => 'Blog'], function () {
        Route::get('/', 'PostController@index')->name('posts.index');
        Route::get('/filter', 'PostController@filter')->name('posts.filter');
        Route::get('/{post}/{slug?}', 'PostController@show')->name('posts.show');

        Route::resource('posts.comments', 'CommentController')->shallow();
    });

    Route::group(['prefix' => 'shop', 'namespace' => 'Shop'], function () {
        Route::get('/', 'ShopController@index')->name('shop.index');
        Route::post('/products/datatable', 'ShopController@datatable')->name('shop.products.datatable');
        Route::get('/products/{id}/{slug?}', 'ShopController@product')->name('shop.products.show');
        Route::get('/cart', 'CartController@show')->name('shop.cart.show');
        Route::get('/cart/{product}/{count}', 'CartController@add')->name('shop.cart.add');
        Route::get('/checkout', 'ShopController@checkout')->name('shop.checkout');
        Route::get('/checkout', 'ShopController@checkout')->name('shop.checkout');

        Route::get('/orders/{order}', 'OrderController@show')->name('orders.show');
        Route::post('/orders', 'OrderController@store')->name('orders.store');
        Route::delete('/orders/{order}', 'OrderController@destroy')->name('orders.destroy');

        Route::resource('products.comments', 'CommentController')->shallow();
    });

    Route::group(['prefix' => 'schools', 'namespace' => 'School'], function () {
        Route::get('/{school}', 'SchoolController@show')->name('schools.show');
    });

    Route::group(['prefix' => 'provinces', 'namespace' => 'Province'], function () {
        Route::get('/', 'ProvinceController@index')->name('provinces.index');
        Route::get('/{province}', 'ProvinceController@show')->name('provinces.show');
    });

    Route::get('/invoices/{invoice}', 'InvoiceController@show')->name('invoices.show');
    Route::post('/invoices/{invoice}/pay', 'InvoiceController@pay')->name('invoices.pay');

    Route::any('/payment/callback/{gateway}/{invoice}', 'PaymentController@callback')->name('payment.callback');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;

/**
 * App\Models\Post
 *
 * @property int $id
 * @property string $title
 * @property string $content
 * @property string|null $image
 * @property int $author_id
 * @property string|null $meta_keywords
 * @property string|null $meta_description
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\User $author
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Comment[] $comments
 * @property-read int|null $comments_count
 * @property-read string $slug
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Tag[] $tags
 * @property-read int|null $tags_count
 * @method static \Illuminate\Database\Eloquent\Builder|Post newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Post newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Post query()
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereAuthorId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereMetaDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereMetaKeywords($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Post whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Post extends Model
{
    /**
     * @return string
     */
    public function getSlugAttribute()
    {
        return slugify($this->title);
    }

    /**
     * @return MorphToMany
     */
    public function tags()
    {
        return $this->morphToMany(Tag::class, 'taggable');
    }

    /**
     * @return array
     */
    public function tagsArray()
    {
        return $this->tags()->pluck('name')->toArray();
    }

    /**
     * @return BelongsTo
     */
    public function author()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return MorphMany
     */
    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }
}

app/Http/Controllers/Admin/Blog/PostController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Http\Controllers\Controller;
use App\Models\Post;
 use App\Models\Tag;
use Auth;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class PostController extends Controller
{
    /**
     * @return Factory|View
     */
    public function index()
    {
        $posts = Post::paginate(10);

        return view('pages.admin.post.index', [
            'posts' => $posts,
        ]);
    }

    /**
     * @return Factory|View
     */
    public function create()
    {
        return view('pages.admin.post.create', [
            'tags' => Tag::all(),
        ]);
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => ['required', 'unique:posts'],
            'tags' => 'required|array',
            'tags.*' => 'exists:tags,id',
            'content' => 'required',
            'image' => 'required|mimes:jpeg,bmp,png,gif,svg|max:4096',
            'meta_keywords' => 'nullable|string',
            'meta_description' => 'nullable|string|min:135|max:160',
        ]);

        $path = $request->file('image')->store('posts');

        $post = new Post();
        $post->title = $request->get('title');
        $post->content = preventXSS($request->get('content'));
        $post->image = $path;
        $post->author_id = Auth::id();
        $post->meta_keywords = $request->get('meta_keywords');
        $post->meta_description = $request->get('meta_description');
        $post->save();

        $post->tags()->attach($request->get('tags'));

        return redirect()->route('admin.blog.posts.index')->with('success', trans('posts.created'));
    }

    /**
     * @param Post $post
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * @param Post $post
     * @return Application|Factory|View
     */
    public function edit(Post $post)
    {
        return view('pages.admin.post.edit', [
            'post' => $post,
            'tags' => Tag::all(),
        ]);
    }

    /**
     * @param Request $request
     * @param Post $post
     * @return RedirectResponse
     */
    public function update(Request $request, Post $post)
    {
        $request->validate([
            'title' => ['required', 'unique:posts,title,' . $post->id],
            'tags' => 'required|array',
            'tags.*' => 'exists:tags,id',
            'content' => 'required',
            'image' => 'nullable|mimes:jpeg,bmp,png,gif,svg|max:4096',
            'meta_keywords' => 'nullable|string',
            'meta_description' => 'nullable|string|min:135|max:160',
        ]);

        $path = $post->image;
        if ($request->file('image')) {
            $path = $request->file('image')->store('posts');
        }

        $post->title = $request->get('title');
        $post->content = preventXSS($request->get('content'));
        $post->image = $path;
        $post->author_id = Auth::id();
        $post->meta_keywords = $request->get('meta_keywords');
        $post->meta_description = $request->get('meta_description');
        $post->save();

        $post->tags()->sync($request->get('tags'));

        return redirect()->route('admin.blog.posts.index')->with('success', trans('posts.updated'));
    }

    /**
     * @param Post $post
     * @return JsonResponse
     * @throws Exception
     */
    public function destroy(Post $post)
    {
        $post->tags()->detach();
        $post->delete();

        return new JsonResponse(['message' => trans('categories.deleted')]);
    }
}

app/Http/Controllers/Front/Blog/PostController.php
<?php

namespace App\Http\Controllers\Front\Blog;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\Tag;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\View\View;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $posts = Post::orderBy('id', 'desc')->paginate(5);
        $tags = Tag::withCount(['posts'])->orderBy('posts_count', 'DESC')->get();
        $popularPosts = Post::inRandomOrder()->limit(3)->get();
        $newestPosts = Post::orderByDesc('id')->limit(3)->get();

        return view('pages.front.blog.index', [
            'posts' => $posts,
            'tags' => $tags,
            'popularPosts' => $popularPosts,
            'newestPosts' => $newestPosts,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function show(int $id)
    {
        $post = Post::whereId($id)->with('comments')->withCount('comments')->first();
        $relatedPosts = Post::where('id', '<>', $id)->limit(6)->get();

        return view('pages.front.blog.show', [
            'post' => $post,
            'relatedPosts' => $relatedPosts,
        ]);
    }

    /**
     * @param Request $request
     * @return Application|Factory|View
     */
    public function filter(Request $request)
    {
        $posts = Tag::findOrFail($request->get('tag'))->posts()->orderBy('id', 'desc')->paginate(5);

        $tags = Tag::withCount(['posts'])->orderBy('posts_count', 'DESC')->get();
        $popularPosts = Post::inRandomOrder()->limit(3)->get();
        $newestPosts = Post::orderByDesc('id')->limit(3)->get();

        return view('pages.front.blog.index', [
            'posts' => $posts,
            'tags' => $tags,
            'popularPosts' => $popularPosts,
            'newestPosts' => $newestPosts,
        ]);
    }
}

resources/views/pages/admin/post/create.blade.php
@extends('pages.admin.layout.base')

@section('title', 'خانه')
@section('post', 'active menu-open')
@section('post2', 'active')

@section('style')
@endsection

@section('header')
    <section class="content-header">
        <h1>
            افزودن مقاله جدید
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i>خانه</a></li>
            <li><a href="#">مقاله ها</a></li>
            <li class="active">افزودن مقاله</li>
        </ol>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <form method="post" action="{{ route('admin.blog.posts.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="box-header"></div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="title">عنوان</label>
                                        <input type="text" class="form-control" id="title" placeholder="عنوان"
                                               value="{{ old('title') }}" name="title">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="tags">برچسب ها</label>
                                        <select type="text" class="form-control select2" id="tags" name="tags[]" multiple="multiple"  style="width: 100%;">
                                            @foreach($tags as $tag)
                                                <option value="{{ $tag->id }}"
                                                    {{in_array($tag->id, old('tags', [])) ? 'selected':''}}>
                                                    {{ $tag->name }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="image">تصویر</label>
                                        <label class="form-control">
                                            <span> انتخاب کنید ... </span>
                                            <input type="file" class="custom-file-input" accept="image/*"
                                                   id="image" name="image" value="{{ old('image') }}"
                                                   hidden>
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <label for="content">محتوا </label>
                                    <textarea id="content" name="content"
                                              style="width: 100%; height: 210px; border: 1px solid #dddddd; padding: 10px;"
                                              class="form-control">{!! old('content') !!}</textarea>
                                </div>
                            </div>

                            <hr>
                            <h5>
                                SEO
                                <small>برای بهتر دیده شدن این بخش را کامل کنید</small>
                            </h5>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="meta_keywords">کلمات کلیدی</label>
                                        <input type="text" class="form-control" id="meta_keywords" placeholder="HTML, CSS, JavaScript"
                                               value="{{ old('meta_keywords')}}" name="meta_keywords">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <label for="meta_description">توضیحات(بین ۱۳۵ تا ۱۶۰ کاراکتر باشد)</label>
                                    <textarea id="meta_description" name="meta_description" minlength="135" maxlength="160"
                                              class="form-control">{{old('meta_description')}}</textarea>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">افزودن مقاله جدید</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection


@section('js')
    <script type="text/javascript" src="{{ asset('assets/admin/adminLTE/components/ckeditor/ckeditor.js')}}"></script>

    <script>
        CKEDITOR.config.contentsLangDirection = 'rtl';
        CKEDITOR.config.language = 'fa';
        CKEDITOR.replace('content');
    </script>
@endsection

resources/views/pages/admin/post/index.blade.php
@extends('pages.admin.layout.base')

@section('title', 'خانه')
@section('post', 'active menu-open')
@section('post1', 'active')

@section('header')
    <section class="content-header">
        <h1>
            مقاله ها <small>لیست</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i>خانه</a></li>
            <li><a href="#">مقاله ها</a></li>
            <li class="active">لیست مقاله ها</li>
        </ol>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">لیست مقاله ها</h3>
                        <a href="{{ route('admin.blog.posts.create') }}" class="btn btn-primary btn-flat pull-left">افزودن
                            مقاله جدید</a>
                    </div>
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>عنوان</th>
                                <th>برچسب ها</th>
                                <th>نویسنده</th>
                                <th>تاریخ ایجاد</th>
                                <th>عملیات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($posts as $post)
                                <tr>
                                    <td>
                                        <a href="{{ route('posts.show', ['post' => $post->id, 'slug' => $post->slug]) }}">
                                            {{ $post->title }}
                                        </a>
                                    </td>
                                    <td>
                                        @foreach($post->tagsArray() as $tag)
                                            <li>{{ $tag }}</li>
                                        @endforeach
                                    </td>
                                    <td>{{ $post->author->full_name }}</td>
                                    <td>{{ jDate($post->created_at, 'dd MMMM yyyy - HH:mm') }}</td>
                                    <td>
                                        <a href="{{ route('admin.blog.posts.edit', ['post' => $post->id]) }}"
                                           type="button" class="btn btn-block btn-primary btn-xs">ویرایش مقاله
                                        </a>
                                        <a type="button" class="btn btn-block btn-danger btn-xs"
                                           onclick="removePost({{ $post->id }})">حذف مقاله</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="mt-2">
                            {{ $posts->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('js')
    <script>
        function removePost(id) {
            let url = "{{ route('admin.blog.posts.destroy', '') }}/" + id
            Swal.fire({
                title: 'آیا مقاله حذف شود؟',
                text: "",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'بله',
                cancelButtonText: 'خیر',
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: "DELETE",
                        url: url,
                        success: function (response) {
                            Swal.fire(
                                response['message'],
                                '',
                                'success'
                            )
                            window.location.reload();
                        },
                        error: function (error) {
                            switch (error.status) {
                                case 422:
                                    let errors = error['responseJSON']['errors'];

                                    for (let i in errors) {
                                        toastr.error(errors[i])
                                    }
                                    break;
                                default:
                                    // 500
                                    toastr.error(error['responseJSON']['message'])
                                    break;
                            }
                        }
                    });
                }
            })
        }
    </script>
@endsection