routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@home')->name('home');
Route::get('/profile', 'ProfileController@profile')->name('profiles.index');
Route::post('/profile', 'ProfileController@update')->name('profiles.update');

Route::resources([
    'users' => 'UserController',
    'admins' => 'AdminController',
    'tags' => 'TagController',
]);

Route::group(['namespace' => 'Course', 'prefix' => 'course', 'as' => 'course.'], function () {
    Route::resources([
        'instructors' => 'InstructorController',
        'courses' => 'CourseController',
        'syllabuses' => 'SyllabusController',
        'categories' => 'CategoryController',
    ]);
});

Route::group(['namespace' => 'Exam', 'prefix' => 'exam' , 'as' => 'exam.'], function () {
    Route::resources([
        'exams' => 'ExamController',
        'questions' => 'QuestionController',
    ]);
});

Route::group(['namespace' => 'Blog', 'prefix' => 'blog', 'as' => 'blog.'], function () {
    Route::resources([
        'posts' => 'PostController',
    ]);

    Route::get('/comments/', 'CommentController@index')->name('posts.comments.index');
    Route::delete('/comments/{comment}', 'CommentController@destroy')->name('posts.comments.destroy');
});

Route::group(['namespace' => 'Shop', 'prefix' => 'shop', 'as' => 'shop.'], function () {
    Route::resources([
        'products' => 'ProductController',
        'categories' => 'CategoryController',
    ]);

    Route::post('/products/{product}/change-status', 'ProductController@changeStatus')->name('products.change-status');

    Route::get('/comments/', 'CommentController@index')->name('products.comments.index');
    Route::delete('/comments/{comment}', 'CommentController@destroy')->name('products.comments.destroy');

    Route::get('/orders/', 'OrderController@index')->name('orders.index');
    Route::post('/orders/{order}/change-status', 'OrderController@changeStatus')->name('orders.change-status');
});

Route::get('/transactions/', 'TransactionController@index')->name('transactions.index');

Route::get('/contact-form/', 'ContactFormController@index')->name('contact-form.index');

routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@home')->name('home');

Route::post('/profile/update', 'ProfileController@update')->name('profile.update');
Route::post('/profile/image/update', 'ProfileController@imageUpdate')->name('profile.image.update');
Route::post('/profile/password/update', 'ProfileController@changePassword')->name('profile.password.change');


Route::group(['prefix' => 'products'], function () {
    Route::post('/', 'ProductController@store')->name('products.store');
    Route::post('/datatable', 'ProductController@datatable')->name('products.datatable');
});

Route::group(['prefix' => 'orders'], function () {
    Route::delete('destroy/{order}', 'OrderController@destroy')->name('orders.destroy');
    Route::get('show/{order}', 'OrderController@show')->name('orders.show');
    Route::get('pay/{order}', 'OrderController@pay')->name('orders.pay');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
    Route::get('/otp', [
        'uses' => 'OtpController@show',
        'as' => 'auth.otp',
        'middleware' => 'guest',
    ]);
    Route::post('/otp/request', [
        'uses' => 'OtpController@request',
        'as' => 'auth.otp.request',
        'middleware' => ['throttle:3,1', 'guest'],
    ]);
    Route::post('/otp/submit', [
        'uses' => 'OtpController@submit',
        'as' => 'auth.otp.submit',
        'middleware' => ['throttle:3,1', 'guest'],
    ]);

    Route::get('sign-up', [
        'uses' => 'SignUpController@show',
        'as' => 'auth.sign-up',
        'middleware' => 'auth',
    ]);
    Route::post('sign-up', [
        'uses' => 'SignUpController@request',
        'middleware' => 'auth',
    ]);

    Route::get('sign-in', [
        'uses' => 'SignInController@show',
        'as' => 'auth.sign-in',
        'middleware' => 'guest',
    ]);
    Route::post('sign-in', [
        'uses' => 'SignInController@request',
        'middleware' => 'guest',
    ]);
    Route::get('sign-out', [
        'uses' => 'SignOutController@handle',
        'as' => 'auth.sign-out',
    ]);
});

//verify email
Route::get('/account/email/verify/{token}', [
    'uses' => 'Account\EmailResetController@verify',
    'as' => 'account.email.verify',
]);

// get all cities of province
Route::get('/cities', 'CityController@get')->name('cities');

Route::post('/upload/image', 'uploadController@dropzone')->name('upload.dropzone');

Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'HomeController@home')->name('home');

    Route::get('/contact-us', 'ContactUsController@show')->name('contact-us');
    Route::post('/contact-us', 'ContactUsController@request');

    Route::get('/search', 'SearchController@search')->name('search');
    Route::get('/courses/search', 'SearchController@courseSearch')->name('course.search');
    Route::get('/posts/search', 'SearchController@postSearch')->name('post.search');
    Route::get('/products/search', 'SearchController@productSearch')->name('product.search');

    Route::group(['prefix' => 'courses', 'namespace' => 'Course'], function () {
        Route::get('/', 'CourseController@index')->name('courses.index');
        Route::get('/{course}/{slug?}', 'CourseController@show')->name('courses.show');

        Route::post('/{course}/reactions', ['as' => 'courses.react', 'uses' => 'CourseController@react']);


        Route::group(['prefix' => 'syllabuses'], function () {
            Route::get('/{syllabus}/{slug?}', 'SyllabusController@show')->name('syllabuses.show');
        });

        Route::get('/instructors/{instructor}/{slug?}', 'InstructorController@show')->name('instructors.show');
    });

    Route::group(['prefix' => 'articles', 'namespace' => 'Blog'], function () {
        Route::get('/', 'PostController@index')->name('posts.index');
        Route::get('/filter', 'PostController@filter')->name('posts.filter');
        Route::get('/{post}/{slug?}', 'PostController@show')->name('posts.show');

        Route::resource('posts.comments', 'CommentController')->shallow();
    });

    Route::group(['prefix' => 'shop', 'namespace' => 'Shop'], function () {
        Route::get('/', 'ShopController@index')->name('shop.index');
        Route::post('/products/datatable', 'ShopController@datatable')->name('shop.products.datatable');
        Route::get('/products/{id}/{slug?}', 'ShopController@product')->name('shop.products.show');
        Route::get('/cart', 'CartController@show')->name('shop.cart.show');
        Route::get('/cart/{product}/{count}', 'CartController@add')->name('shop.cart.add');
        Route::get('/checkout', 'ShopController@checkout')->name('shop.checkout');
        Route::get('/checkout', 'ShopController@checkout')->name('shop.checkout');

        Route::get('/orders/{order}', 'OrderController@show')->name('orders.show');
        Route::post('/orders', 'OrderController@store')->name('orders.store');
        Route::delete('/orders/{order}', 'OrderController@destroy')->name('orders.destroy');

        Route::resource('products.comments', 'CommentController')->shallow();
    });

    Route::group(['prefix' => 'schools', 'namespace' => 'School'], function () {
        Route::get('/{school}', 'SchoolController@show')->name('schools.show');
    });

    Route::group(['prefix' => 'provinces', 'namespace' => 'Province'], function () {
        Route::get('/', 'ProvinceController@index')->name('provinces.index');
        Route::get('/{province}', 'ProvinceController@show')->name('provinces.show');
    });

    Route::get('/invoices/{invoice}', 'InvoiceController@show')->name('invoices.show');
    Route::post('/invoices/{invoice}/pay', 'InvoiceController@pay')->name('invoices.pay');

    Route::any('/payment/callback/{gateway}/{invoice}', 'PaymentController@callback')->name('payment.callback');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * App\Models\User
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $surname
 * @property string $cell
 * @property string|null $email
 * @property int|null $province_id
 * @property int|null $city_id
 * @property int|null $school_id
 * @property string|null $grade
 * @property string $image
 * @property \Illuminate\Support\Carbon|null $cell_verified_at
 * @property \Illuminate\Support\Carbon|null $email_verified_at
 * @property string|null $password
 * @property string|null $remember_token
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property-read \App\Models\City|null $city
 * @property-read string $full_name
 * @property-read \App\Models\Instructor|null $instructor
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read int|null $notifications_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Order[] $orders
 * @property-read int|null $orders_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Product[] $products
 * @property-read int|null $products_count
 * @property-read \App\Models\Province|null $province
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Role[] $roles
 * @property-read int|null $roles_count
 * @property-read \App\Models\School|null $school
 * @property-read \App\Models\UserEmailReset|null $userEmailReset
 * @method static \Illuminate\Database\Eloquent\Builder|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User newQuery()
 * @method static \Illuminate\Database\Query\Builder|User onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|User query()
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCell($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCellVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCityId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereGrade($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereProvinceId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereSchoolId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereSurname($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|User withTrashed()
 * @method static \Illuminate\Database\Query\Builder|User withoutTrashed()
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    protected $guarded = ['id', 'created_at', 'updated_at'];

    protected $hidden = [
        'password',
        'remember_token',
        'cell_verified_at',
        'updated_at',
        'deleted_at',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'cell_verified_at' => 'datetime',
    ];

    public $appends = ['full_name'];

    /**
     * @param $value
     * @return string
     */
    public function getFullNameAttribute($value)
    {
        return $this->name . ' ' . $this->surname;
    }

    /**
     * @return HasOne
     */
    public function instructor()
    {
        return $this->hasOne(Instructor::Class);
    }

    /**
     * @return bool
     */
    public function isInstructor()
    {
        return $this->instructor != null;
    }

    /**
     * @return bool
     */
    public function isStudent()
    {
        return $this->grade != null and $this->school_id != null;
    }

    /**
     * @return BelongsTo
     */
    public function school(): BelongsTo
    {
        return $this->belongsTo(School::class);
    }

    /**
     * @return HasMany
     */
    public function products(): HasMany
    {
        return $this->hasMany(Product::class, 'owner_id');
    }

    /**
     * @return HasMany
     */
    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    /**
     * @param string|null $value
     * @return string
     */
    public function getImageAttribute(?string $value)
    {
        if ($value) {
            return asset('storage/' . $value);
        } elseif ($this->isAdmin()) {
            return asset('assets/img/avatars/avatar5.png');
        } else {
            return asset('assets/img/avatars/avatar.png');
        }
    }

    /**
     * @return BelongsToMany
     */
    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    /**
     * @param int $roleId
     * @return bool
     */
    public function hasRole(int $roleId): bool
    {
        foreach ($this->roles as $role) {
            if ($role->id == $roleId) {
                return true;
            }
        }

        return false;
    }

    /**
     * @param string $permissions
     * @return bool
     */
    public function hasPermission(string $permissions): bool
    {
        $permissions = explode('|', $permissions);

        foreach ($this->roles as $role) {
            foreach ($role->permissions() as $p) {
                if (in_array($p, $permissions)) {
                    return true;
                }
            }
        }

        return false;
    }

    public function isAdmin(): bool
    {
        return $this->roles()->count() > 0;
    }

    public function isSuperAdmin(): bool
    {
        $this->load('roles');

        return $this->roles()->where('title', 'super_admin')->exists();
    }

    /**
     * @return HasOne
     */
    public function userEmailReset()
    {
        return $this->hasOne(UserEmailReset::class);
    }

    /**
     * @return BelongsTo
     */
    public function province(): BelongsTo
    {
        return $this->belongsTo(Province::class, 'province_id');
    }

    /**
     * @return BelongsTo
     */
    public function city(): BelongsTo
    {
        return $this->belongsTo(City::class, 'city_id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Routing\Controller;
use Illuminate\View\View;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $users = User::whereDoesntHave('roles')->paginate(10);

        return view('pages.admin.user.index', [
            'users' => $users,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return Factory|View
     */
    public function show(User $user)
    {
        return view('pages.admin.user.show', [
            'user' => $user,
            'orders' => $user->orders,
        ]);
    }
}

resources/views/pages/admin/user/index.blade.php
@extends('pages.admin.layout.base')

@section('title', 'لیست کاربران')
@section('user', 'active menu-open')
@section('user1', 'active')

@section('header')
    <section class="content-header">
        <h1>
            کاربران <small>لیست</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home')}}"><i class="fa fa-dashboard"></i>خانه</a></li>
            <li><a href="#">کاربران</a></li>
            <li class="active">لیست کاربران</li>
        </ol>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">لیست کاربران</h3>
                    </div>
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>نام</th>
                                <th>تلفن</th>
                                <th>ایمیل</th>
                                <th>تاریخ ایجاد</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>
                                        <a href="{{ route('admin.users.show', $user->id) }}">
                                            {{ $user->full_name}}
                                        </a>
                                    </td>
                                    <td>{{ $user->cell}}</td>
                                    <td>{{ $user->email}}</td>
                                    <td>{{jDate($user->created_at, 'dd MMMM yyyy - HH:mm')}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="mt-2">
                            {{ $users->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/admin/user/show.blade.php
@extends('pages.admin.layout.base')

@section('title', $user->full_name)
@section('user', 'active menu-open')
@section('user2', 'active')

@section('header')
    <section class="content-header">
        <h1>
            کاربران <small>لیست</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home')}}"><i class="fa fa-dashboard"></i>خانه</a></li>
            <li><a href="#">کاربران</a></li>
            <li class="active">لیست کاربران</li>
        </ol>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">{{ $user->full_name }}</h3>
                    </div>
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <tbody>
                            <tr>
                                <td>نام</td>
                                <td>{{ $user->full_name}}</td>
                            </tr>
                            <tr>
                                <td>تلفن</td>
                                <td>{{ $user->cell}}</td>
                            </tr>
                            <tr>
                                <td>ایمیل</td>
                                <td>{{ $user->email}}</td>
                            </tr>
                            <tr>
                                <td>تاریخ نام نویسی</td>
                                <td>{{jDate($user->created_at, 'dd MMMM yyyy - HH:mm')}}</td>
                            </tr>
                            </tbody>
                        </table>
                        <br>

                        @if($orders->count())
                            <h5 class="box-title">سفارشات</h5>
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>خریدار</th>
                                    <th></th>
                                    <th>قیمت</th>
                                    <th>قیمت کل</th>
                                    <th>تاریخ</th>
                                    <th>آدرس</th>
                                    <th>وضعیت</th>
                                    <th>-</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($orders as $order)
                                    <tr>
                                        <td>
                                            <a href="{{ route('admin.users.show', $order->user->id) }}">
                                                {{ $order->user->full_name }}
                                            </a>
                                        </td>
                                        <td>
                                            <ul class="pr-1">
                                                @foreach($order->products() as $product)
                                                    <li>
                                                        @if($product->type === \App\Enums\Shop\ProductType::Physical)
                                                            <span>{{ $product->quantity }}</span>
                                                            <span> عدد </span>
                                                            <span>{{ $product->name }}</span>
                                                        @else
                                                            <span>{{ $product->name }}</span>
                                                        @endif
                                                    </li>
                                                @endforeach
                                            </ul>
                                        </td>
                                        <td>
                                            <ul class="pr-1">
                                                @foreach($order->products() as $product)
                                                    <li>
                                                        <span>{{ number_format($product->price) }}</span>
                                                    </li>
                                                @endforeach
                                            </ul>
                                        </td>
                                        <td>{{ number_format($order->total_price) }}</td>
                                        <td>{{ jDate($order->created_at, 'dd MMMM yyyy - HH:mm') }}</td>
                                        <td>{{ $order->address->toString() }}</td>
                                        <td>{{ $order->status() }}</td>
                                        <td>
                                            @if($order->status == \App\Enums\InvoiceableStatus::Payed)
                                                <a type="button" class="btn btn-block btn-default btn-xs"
                                                   onclick="makeShipped({{ $order->id}})">
                                                    ارسال شد
                                                </a>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection