routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@home')->name('home');
Route::get('/profile', 'ProfileController@profile')->name('profiles.index');
Route::post('/profile', 'ProfileController@update')->name('profiles.update');

Route::resources([
    'users' => 'UserController',
    'admins' => 'AdminController',
    'tags' => 'TagController',
]);

Route::group(['namespace' => 'Course', 'prefix' => 'course', 'as' => 'course.'], function () {
    Route::resources([
        'instructors' => 'InstructorController',
        'courses' => 'CourseController',
        'syllabuses' => 'SyllabusController',
        'categories' => 'CategoryController',
    ]);
});

Route::group(['namespace' => 'Exam', 'prefix' => 'exam' , 'as' => 'exam.'], function () {
    Route::resources([
        'exams' => 'ExamController',
        'questions' => 'QuestionController',
    ]);
});

Route::group(['namespace' => 'Blog', 'prefix' => 'blog', 'as' => 'blog.'], function () {
    Route::resources([
        'posts' => 'PostController',
    ]);

    Route::get('/comments/', 'CommentController@index')->name('posts.comments.index');
    Route::delete('/comments/{comment}', 'CommentController@destroy')->name('posts.comments.destroy');
});

Route::group(['namespace' => 'Shop', 'prefix' => 'shop', 'as' => 'shop.'], function () {
    Route::resources([
        'products' => 'ProductController',
        'categories' => 'CategoryController',
    ]);

    Route::post('/products/{product}/change-status', 'ProductController@changeStatus')->name('products.change-status');

    Route::get('/comments/', 'CommentController@index')->name('products.comments.index');
    Route::delete('/comments/{comment}', 'CommentController@destroy')->name('products.comments.destroy');

    Route::get('/orders/', 'OrderController@index')->name('orders.index');
    Route::post('/orders/{order}/change-status', 'OrderController@changeStatus')->name('orders.change-status');
});

Route::get('/transactions/', 'TransactionController@index')->name('transactions.index');

Route::get('/contact-form/', 'ContactFormController@index')->name('contact-form.index');

routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@home')->name('home');

Route::post('/profile/update', 'ProfileController@update')->name('profile.update');
Route::post('/profile/image/update', 'ProfileController@imageUpdate')->name('profile.image.update');
Route::post('/profile/password/update', 'ProfileController@changePassword')->name('profile.password.change');


Route::group(['prefix' => 'products'], function () {
    Route::post('/', 'ProductController@store')->name('products.store');
    Route::post('/datatable', 'ProductController@datatable')->name('products.datatable');
});

Route::group(['prefix' => 'orders'], function () {
    Route::delete('destroy/{order}', 'OrderController@destroy')->name('orders.destroy');
    Route::get('show/{order}', 'OrderController@show')->name('orders.show');
    Route::get('pay/{order}', 'OrderController@pay')->name('orders.pay');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
    Route::get('/otp', [
        'uses' => 'OtpController@show',
        'as' => 'auth.otp',
        'middleware' => 'guest',
    ]);
    Route::post('/otp/request', [
        'uses' => 'OtpController@request',
        'as' => 'auth.otp.request',
        'middleware' => ['throttle:3,1', 'guest'],
    ]);
    Route::post('/otp/submit', [
        'uses' => 'OtpController@submit',
        'as' => 'auth.otp.submit',
        'middleware' => ['throttle:3,1', 'guest'],
    ]);

    Route::get('sign-up', [
        'uses' => 'SignUpController@show',
        'as' => 'auth.sign-up',
        'middleware' => 'auth',
    ]);
    Route::post('sign-up', [
        'uses' => 'SignUpController@request',
        'middleware' => 'auth',
    ]);

    Route::get('sign-in', [
        'uses' => 'SignInController@show',
        'as' => 'auth.sign-in',
        'middleware' => 'guest',
    ]);
    Route::post('sign-in', [
        'uses' => 'SignInController@request',
        'middleware' => 'guest',
    ]);
    Route::get('sign-out', [
        'uses' => 'SignOutController@handle',
        'as' => 'auth.sign-out',
    ]);
});

//verify email
Route::get('/account/email/verify/{token}', [
    'uses' => 'Account\EmailResetController@verify',
    'as' => 'account.email.verify',
]);

// get all cities of province
Route::get('/cities', 'CityController@get')->name('cities');

Route::post('/upload/image', 'uploadController@dropzone')->name('upload.dropzone');

Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'HomeController@home')->name('home');

    Route::get('/contact-us', 'ContactUsController@show')->name('contact-us');
    Route::post('/contact-us', 'ContactUsController@request');

    Route::get('/search', 'SearchController@search')->name('search');
    Route::get('/courses/search', 'SearchController@courseSearch')->name('course.search');
    Route::get('/posts/search', 'SearchController@postSearch')->name('post.search');
    Route::get('/products/search', 'SearchController@productSearch')->name('product.search');

    Route::group(['prefix' => 'courses', 'namespace' => 'Course'], function () {
        Route::get('/', 'CourseController@index')->name('courses.index');
        Route::get('/{course}/{slug?}', 'CourseController@show')->name('courses.show');

        Route::post('/{course}/reactions', ['as' => 'courses.react', 'uses' => 'CourseController@react']);


        Route::group(['prefix' => 'syllabuses'], function () {
            Route::get('/{syllabus}/{slug?}', 'SyllabusController@show')->name('syllabuses.show');
        });

        Route::get('/instructors/{instructor}/{slug?}', 'InstructorController@show')->name('instructors.show');
    });

    Route::group(['prefix' => 'articles', 'namespace' => 'Blog'], function () {
        Route::get('/', 'PostController@index')->name('posts.index');
        Route::get('/filter', 'PostController@filter')->name('posts.filter');
        Route::get('/{post}/{slug?}', 'PostController@show')->name('posts.show');

        Route::resource('posts.comments', 'CommentController')->shallow();
    });

    Route::group(['prefix' => 'shop', 'namespace' => 'Shop'], function () {
        Route::get('/', 'ShopController@index')->name('shop.index');
        Route::post('/products/datatable', 'ShopController@datatable')->name('shop.products.datatable');
        Route::get('/products/{id}/{slug?}', 'ShopController@product')->name('shop.products.show');
        Route::get('/cart', 'CartController@show')->name('shop.cart.show');
        Route::get('/cart/{product}/{count}', 'CartController@add')->name('shop.cart.add');
        Route::get('/checkout', 'ShopController@checkout')->name('shop.checkout');
        Route::get('/checkout', 'ShopController@checkout')->name('shop.checkout');

        Route::get('/orders/{order}', 'OrderController@show')->name('orders.show');
        Route::post('/orders', 'OrderController@store')->name('orders.store');
        Route::delete('/orders/{order}', 'OrderController@destroy')->name('orders.destroy');

        Route::resource('products.comments', 'CommentController')->shallow();
    });

    Route::group(['prefix' => 'schools', 'namespace' => 'School'], function () {
        Route::get('/{school}', 'SchoolController@show')->name('schools.show');
    });

    Route::group(['prefix' => 'provinces', 'namespace' => 'Province'], function () {
        Route::get('/', 'ProvinceController@index')->name('provinces.index');
        Route::get('/{province}', 'ProvinceController@show')->name('provinces.show');
    });

    Route::get('/invoices/{invoice}', 'InvoiceController@show')->name('invoices.show');
    Route::post('/invoices/{invoice}/pay', 'InvoiceController@pay')->name('invoices.pay');

    Route::any('/payment/callback/{gateway}/{invoice}', 'PaymentController@callback')->name('payment.callback');
});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Comment
 *
 * @property int $id
 * @property string $body
 * @property string $commentable_type
 * @property int $commentable_id
 * @property int|null $parent_id
 * @property int|null $user_id
 * @property string|null $name
 * @property string|null $email
 * @property string|null $ip
 * @property int $status
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read Model|\Eloquent $commentable
 * @property-read mixed $image
 * @property-read \App\Models\User|null $user
 * @method static \Illuminate\Database\Eloquent\Builder|Comment newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Comment newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Comment query()
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereBody($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereCommentableId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereCommentableType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereIp($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereParentId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Comment whereUserId($value)
 * @mixin \Eloquent
 */
class Comment extends Model
{

    public function commentable()
    {
        return $this->morphTo();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getImageAttribute($value)
    {
        if ($this->user_id) {
            return $this->user->image;
        }
        return asset('assets/img/avatars/avatar.png');
    }
}

app/Http/Controllers/Admin/Blog/CommentController.php
<?php

namespace App\Http\Controllers\Admin\Blog;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\Comment;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\View\View;

class CommentController extends Controller
{
    /**
     * @return Factory|View
     */
    public function index()
    {
        $comments = Comment::whereCommentableType(Post::class)->paginate(12);

        return view('pages.admin.comment.index', [
            'comments' => $comments,
        ]);
    }


    /**
     * @param Comment $comment
     * @return JsonResponse
     * @throws Exception
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();

        return new JsonResponse(['message' => trans('comments.deleted')]);
    }
}

app/Http/Controllers/Admin/Shop/CommentController.php
<?php

namespace App\Http\Controllers\Admin\Shop;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use App\Models\Product;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\View\View;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $comments = Comment::whereCommentableType(Product::class)->paginate(12);

        return view('pages.admin.comment.index', [
            'comments' => $comments,
        ]);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param Comment $comment
     * @return JsonResponse
     * @throws Exception
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();

        return new JsonResponse(['message' => trans('comments.deleted')]);
    }
}

app/Http/Controllers/Front/Blog/CommentController.php
<?php

namespace App\Http\Controllers\Front\Blog;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\Comment;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class CommentController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param Post $post
     * @return RedirectResponse
     */
    public function store(Request $request, Post $post)
    {
        $validator = Validator::make($request->all(), [
            'name' => [Rule::requiredIf(Auth::guest())],
            'cell' => [Rule::requiredIf(Auth::guest()), 'cell'],
            'body' => ['required', 'max:1000'],
        ]);

        if ($validator->fails()) {
            return Redirect::to(URL::previous() . "#leave-comment")->withErrors($validator)->withInput();
        }

        $comment = new Comment();
        $comment->ip = $request->ip();
        $comment->commentable_type = Post::class;
        $comment->commentable_id = $post->id;
        $comment->user_id = Auth::check() ? Auth::id() : null;
        $comment->name = $request->get('name');
        $comment->cell = $request->get('cell');
        $comment->body = $request->get('body');
        $comment->save();

        return back()->with('success', trans('comments.created'));
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param Comment $comment
     */
    public function destroy(Comment $comment)
    {
        //
    }
}

app/Http/Controllers/Front/Shop/CommentController.php
<?php

namespace App\Http\Controllers\Front\Shop;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\Comment;
use App\Models\Product;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class CommentController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param Product $product
     * @return RedirectResponse
     */
    public function store(Request $request, Product $product)
    {
        $validator = Validator::make($request->all(), [
            'name' => [Rule::requiredIf(Auth::guest())],
            'cell' => [Rule::requiredIf(Auth::guest()), 'cell'],
            'body' => ['required', 'max:1000'],
        ]);

        if ($validator->fails()) {
            return Redirect::to(URL::previous() . "#leave-comment")->withErrors($validator)->withInput();
        }

        $comment = new Comment();
        $comment->ip = $request->ip();
        $comment->commentable_type = Product::class;
        $comment->commentable_id = $product->id;
        $comment->user_id = Auth::check() ? Auth::id() : null;
        $comment->name = $request->get('name');
        $comment->cell = $request->get('cell');
        $comment->body = $request->get('body');
        $comment->save();

        return back()->with('success', trans('comments.created'));
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param Comment $comment
     */
    public function destroy(Comment $comment)
    {
        //
    }
}

resources/views/pages/admin/comment/index.blade.php
@extends('pages.admin.layout.base')

@section('title', 'خانه')
@section('comment', 'active menu-open')
@section('comment1', 'active')

@section('header')
    <section class="content-header">
        <h1>
            دیدگاه ها <small>لیست</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i>خانه</a></li>
            <li><a href="#">دیدگاه ها</a></li>
            <li class="active">لیست دیدگاه ها</li>
        </ol>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">لیست دیدگاه ها</h3>
                    </div>
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>متن</th>
                                <th>برای</th>
                                <th>نویسنده</th>
                                <th>تاریخ ایجاد</th>
                                <th>عملیات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($comments as $comment)
                                <tr>
                                    <td>{{ $comment->body }}</td>
                                    <td>
                                        <a href="{{ route('posts.show', ['post' => $comment->commentable_id, 'slug' => $comment->commentable->title]) }}">
                                            {{ $comment->commentable->title }}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="mailto:{{ $comment->email }}">{{ $comment->name }}</a>
                                    </td>
                                    <td>{{ jDate($comment->created_at, 'dd MMMM yyyy - HH:mm') }}</td>
                                    <td>
                                        <a type="button" class="btn btn-block btn-danger btn-xs"
                                           onclick="removePost({{ $comment->id }})">حذف دیدگاه</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="mt-2">
                            {{ $comments->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('js')
    <script>
        function removePost(id) {
            let url = "{{ route('admin.blog.posts.comments.destroy', '') }}/" + id
            Swal.fire({
                title: 'آیا دیدگاه حذف شود؟',
                text: "",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'بله',
                cancelButtonText: 'خیر',
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: "DELETE",
                        url: url,
                        success: function (response) {
                            Swal.fire(
                                'دیدگاه با موفقیت حذف شد',
                                '',
                                'success'
                            )
                            window.location.reload();
                        },
                        error: function (error) {
                            switch (error.status) {
                                case 422:
                                    let errors = error['responseJSON']['errors'];

                                    for (let i in errors) {
                                        toastr.error(errors[i])
                                    }
                                    break;
                                default:
                                    // 500
                                    toastr.error(error['responseJSON']['message'])
                                    break;
                            }
                        }
                    });
                }
            })
        }
    </script>
@endsection